// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybgbgfkvymypbcequlhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZ2JnZmt2eW15cGJjZXF1bGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDM1NzAsImV4cCI6MjA3MjIxOTU3MH0.zHxagCeRMLocdFkkgXsWxdiCvlab-Olx5q5BQPanjY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});